name: Publish Python 🐍 distributions 📦 to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - "published"

jobs:
  wheel:
    name: Package 📦 wheel
    runs-on: windows-latest
    steps:

    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "2.7.x"

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
        
    - name: Build a wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        
    - name: Upload wheel as release artifact
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        files: "./dist/*.whl"

    - name: Publish distribution 📦 to PyPI
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
